---
- hosts: all
  sudo: yes
  handlers:
    - include: handlers/main.yml
  tasks:
    - include: tasks/deployer.yml
    - include: tasks/base_packages.yml
    - include: tasks/database.yml
    - include: tasks/foreman.yml
    - include: tasks/elasticsearch.yml
    - include: tasks/nginx.yml
    - include: tasks/jenkins.yml
    - include: tasks/jenkins_cli.yml
    - include: tasks/jenkins_plugins.yml
    - include: tasks/jenkins_config.yml
    - include: tasks/jenkins_jobs.yml
