---
- hosts: all
  sudo: yes
  handlers:
    - include: handlers/main.yml
  tasks:
    - include: tasks/env_vars.yml
    - include: tasks/non_interactive_shell_vars.yml
    - include: tasks/deployer.yml
    - include: tasks/base_packages.yml
    - include: tasks/app_dir.yml
    - include: tasks/database.yml
    - include: tasks/foreman.yml
    - include: tasks/elasticsearch.yml
    - include: tasks/nginx.yml
