---
# Handle plugins
# If Jenkins is installed or updated, wait for pulling the Jenkins CLI, assuming 10s should be sufficiant


- name: 15s delay while starting Jenkins
  wait_for: port=8080 delay=15
  when: jenkins_install.changed

# Get CLI
- get_url: url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest=/var/lib/jenkins/jenkins-cli.jar mode=0440

# Get latest Jenkins update file
- name: Get Jenkins updates
  action: get_url url=http://updates.jenkins-ci.org/update-center.json dest=/var/lib/jenkins/updates_jenkins.json thirsty=yes mode=0440
  register: jenkins_updates

# Jenkins Update-center
- name: Update-center Jenkins
  action: "shell cat /var/lib/jenkins/updates_jenkins.json | sed '1d;$d' | curl -X POST -H 'Accept: application/json' -d @- http://localhost:8080/updateCenter/byId/default/postBack"
  when: jenkins_updates.changed
  notify: restart jenkins